export const MODAL_STATUS = {
  OPEN: 1,
  CLOSE: 2,
};

export const MODAL_TYPE = {
  SCENIC_SPOT_INTRODUCTION: 0,
  SCENIC_SPOT_GUIDE: 1,
  ENGLISH_TOUR_GUIDE: 2,
  CONTENT_INNOVATION: 3,
  PERSONAL_GRADE: 4,
};
